### ISSUE TITLE
Fingerprints containing bytes where the high nibble is zero are displayed incorrectly

### ISSUE THREAD

**Issue by rob-smallshire** [rkluszczynski/avro-cli#30]
The code which converts the fingerprint to a hexadecimal representation is incorrect.

For example, this sha-256 shows the correct hash first, and the hash as created by `avro-cli` second.

```
correct  c32c497df6730c97fa07362aa5023f37d49a027ec452360778114cf427965add
                     -     -       -         -         -
avro-cli c32c497df673c97fa7362aa523f37d49a27ec45236778114cf427965add
```

The schema in this case is simply `{"type": "long"}`

Fingerprints containing zeros only in the _low_ nibble of bytes are rendered correctly, for example, this MD5 fingerprint:

```
bfc71a62f38b99d6a93690deeb4b3af6
```

**Comment by rkluszczynski** [comment]
Hello @rob-smallshire,
thanks a lot for pull request and fix. Do you need a release right now or could it be postponed a bit?

I asking, because I'm working on feature #22. The plan would be as follows: if I won't be able to finish it in two weeks, I will release new version with your fix. Is it OK for you?

Kind regards,
Rafal

**Comment by rob-smallshire** [comment]
A release is not urgent for me. I can use my local build with the fix until a new release is convenient for you.

**Comment by rkluszczynski** [comment]
@rob-smallshire So it is settled:) I will try to finish feature #22 before next release. 

Thanks again for contribution! :)
